//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeMeMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AE
    {
        public AE()
        {
            this.AEDettaglio = new HashSet<AEDettaglio>();
        }
    
        public int idAE { get; set; }
        public int idPaziente { get; set; }
        public System.DateTime dataInserimento { get; set; }
        public string userName { get; set; }
        public System.DateTime dataAE { get; set; }
        public string note { get; set; }
    
        public virtual ICollection<AEDettaglio> AEDettaglio { get; set; }
        public virtual Anagrafica Anagrafica { get; set; }
    }
}
