//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeMeMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AEDettaglio
    {
        public int idAEDettaglio { get; set; }
        public int idAE { get; set; }
        public int tipoEvento { get; set; }
        public string tipoEventoAltro { get; set; }
        public int serietaEvento { get; set; }
        public int reazioneFarmaco { get; set; }
        public int serietaGrado { get; set; }
        public System.DateTime dataInizio { get; set; }
        public Nullable<System.DateTime> dataFine { get; set; }
        public int outcome { get; set; }
    
        public virtual AE AE { get; set; }
        public virtual LUAE_Grado LUAE_Grado { get; set; }
        public virtual LUAE_Outcome LUAE_Outcome { get; set; }
        public virtual LUAE_TipoEvento LUAE_TipoEvento { get; set; }
    }
}
