//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeMeMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anagrafica
    {
        public Anagrafica()
        {
            this.AE = new HashSet<AE>();
            this.AssegnazioniRegistro = new HashSet<AssegnazioniRegistro>();
            this.KitFlaconiAssegnazione = new HashSet<KitFlaconiAssegnazione>();
            this.SAE = new HashSet<SAE>();
            this.StatiRegistro = new HashSet<StatiRegistro>();
        }
    
        public int idPaziente { get; set; }
        public string codPaziente { get; set; }
        public string userName { get; set; }
        public System.DateTime data { get; set; }
        public int famiglia { get; set; }
        public int parentela { get; set; }
        public int randomizzazioneDieta { get; set; }
        public Nullable<System.DateTime> dataRandomizzazioneDieta { get; set; }
        public byte[] randomizzazioneTrattamento { get; set; }
        public Nullable<System.DateTime> dataRandomizzazioneTrattamento { get; set; }
        public string nome { get; set; }
        public string cognome { get; set; }
        public string indirizzo { get; set; }
        public string provincia { get; set; }
        public string comune { get; set; }
        public string localita { get; set; }
        public string cap { get; set; }
        public System.DateTime datanascita { get; set; }
        public string comuneNascita { get; set; }
        public string cfiscale { get; set; }
        public string sesso { get; set; }
        public Nullable<int> statocivile { get; set; }
        public Nullable<int> istruzione { get; set; }
        public Nullable<int> professione { get; set; }
        public string telefonoFisso { get; set; }
        public string telefonoLavoro { get; set; }
        public string telefonoCellulare { get; set; }
        public string email { get; set; }
        public string medicoNome { get; set; }
        public string medicoCognome { get; set; }
        public string medicoIndirizzo { get; set; }
        public string medicoCitta { get; set; }
        public string medicoTelefonoStudio { get; set; }
        public string medicoTelefonoCellulare { get; set; }
        public string riferimentoNome { get; set; }
        public string riferimentoCognome { get; set; }
        public string riferimentoTelefono { get; set; }
        public bool consensoPrivacy { get; set; }
        public bool consensoInformato { get; set; }
        public Nullable<System.DateTime> dataConsensoInformato { get; set; }
        public bool studioGeneticaPartecipazione { get; set; }
        public bool studioGeneticaUtilizzo { get; set; }
        public bool altriStudiConservazione { get; set; }
        public bool studioGeneticaContatti { get; set; }
        public bool dropOut { get; set; }
        public Nullable<System.DateTime> fromTevere { get; set; }
        public System.Guid idAnonimo { get; set; }
    
        public virtual ICollection<AE> AE { get; set; }
        public virtual Comuni Comuni { get; set; }
        public virtual LUIParentela LUIParentela { get; set; }
        public virtual LUIstruzione LUIstruzione { get; set; }
        public virtual LUProfessione LUProfessione { get; set; }
        public virtual LUStatoCivile LUStatoCivile { get; set; }
        public virtual ICollection<AssegnazioniRegistro> AssegnazioniRegistro { get; set; }
        public virtual ICollection<KitFlaconiAssegnazione> KitFlaconiAssegnazione { get; set; }
        public virtual ICollection<SAE> SAE { get; set; }
        public virtual ICollection<StatiRegistro> StatiRegistro { get; set; }
    }
}
