//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeMeMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Antropometria
    {
        public int idStatoRegistro { get; set; }
        public System.DateTime dataInserimento { get; set; }
        public string userName { get; set; }
        public System.DateTime data { get; set; }
        public decimal altezza { get; set; }
        public decimal peso { get; set; }
        public decimal circonferenzaVita { get; set; }
        public decimal circonferenzaFianchi { get; set; }
        public int pressioneMax { get; set; }
        public int pressioneMin { get; set; }
        public int pulsazioni { get; set; }
        public bool terapiaIpertensione { get; set; }
        public bool terapiaIpercolesterolemia { get; set; }
        public bool terapiaIpertrigliceridemia { get; set; }
        public bool cardioaspirina { get; set; }
        public string note { get; set; }
    
        public virtual StatiRegistro StatiRegistro { get; set; }
    }
}
