//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeMeMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssegnazioniElenco
    {
        public AssegnazioniElenco()
        {
            this.AssegnazioniRegistro = new HashSet<AssegnazioniRegistro>();
            this.KitFlaconiAssegnazione = new HashSet<KitFlaconiAssegnazione>();
        }
    
        public int idAssegnazioneElenco { get; set; }
        public string descrizione { get; set; }
        public string descrizioneForm { get; set; }
        public string fase { get; set; }
        public string istruzioni { get; set; }
        public string posologiaFlaconi { get; set; }
        public int durataMesi { get; set; }
        public int dosaggioPieno { get; set; }
        public bool mezzoDosaggio { get; set; }
    
        public virtual ICollection<AssegnazioniRegistro> AssegnazioniRegistro { get; set; }
        public virtual ICollection<KitFlaconiAssegnazione> KitFlaconiAssegnazione { get; set; }
    }
}
