//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeMeMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssegnazioneFarmaco
    {
        public int idAssegnazioneRegistro { get; set; }
        public System.DateTime dataInserimento { get; set; }
        public string userName { get; set; }
        public int dosaggioPieno { get; set; }
        public int flaconiAssegnati { get; set; }
        public System.DateTime dataConsegna { get; set; }
        public int pilloleAssunte { get; set; }
        public bool effettiCollaterali { get; set; }
        public string osservazioni { get; set; }
    
        public virtual AssegnazioniRegistro AssegnazioniRegistro { get; set; }
    }
}
