//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeMeMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttivitaFisica
    {
        public int idStatoRegistro { get; set; }
        public System.DateTime dataInserimento { get; set; }
        public string userName { get; set; }
        public System.DateTime data { get; set; }
        public short attivitaVigorose { get; set; }
        public Nullable<short> attivitaVigoroseSettimanaDurata { get; set; }
        public bool attivitaVigoroseSettimanaNrNr { get; set; }
        public Nullable<short> attivitaVigoroseTipo { get; set; }
        public string attivitaVigoroseGiornoDurata { get; set; }
        public bool attivitaVigoroseGiornoNrNr { get; set; }
        public short camminata { get; set; }
        public Nullable<short> camminataSettimanaDurata { get; set; }
        public bool camminataSettimanaDurataNsNr { get; set; }
        public Nullable<short> camminataTipo { get; set; }
        public string camminataGiornoDurata { get; set; }
        public bool camminataGiornoDurataNsNr { get; set; }
        public short attivitaModerata { get; set; }
        public Nullable<short> attivitaModerataSettimanaDurata { get; set; }
        public bool attivitaModerataSettimanaDurataNsNr { get; set; }
        public Nullable<short> attivitaModerataTipo { get; set; }
        public string attivitaModerataGiornoDurata { get; set; }
        public bool attivitaModerataGiornoDurataNsNr { get; set; }
        public Nullable<short> attivitaSedentariaSettimanaDurata { get; set; }
        public bool attivitaSedentariaSettimanaDurataNsNr { get; set; }
        public Nullable<short> attivitaSedentariaTipo { get; set; }
        public string attivitaSedentariaMercolediDurata { get; set; }
        public bool attivitaSedentariaMercolediDurataNsNr { get; set; }
        public string sonnoLetto { get; set; }
        public Nullable<short> sonnoAddormentamento { get; set; }
        public string alzata { get; set; }
        public Nullable<short> durataSonno { get; set; }
        public Nullable<short> qualitaSonno { get; set; }
    
        public virtual StatiRegistro StatiRegistro { get; set; }
    }
}
