//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeMeMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comuni
    {
        public Comuni()
        {
            this.Anagrafica = new HashSet<Anagrafica>();
        }
    
        public string CodiceIstatComune { get; set; }
        public string CodiceRegione { get; set; }
        public string CodiceProvincia { get; set; }
        public string CodiceComune { get; set; }
        public string Comune { get; set; }
        public string ProvinciaSigla { get; set; }
        public string Provincia { get; set; }
    
        public virtual ICollection<Anagrafica> Anagrafica { get; set; }
    }
}
