//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeMeMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drop
    {
        public int idDrop { get; set; }
        public int idStatoRegistro { get; set; }
        public System.DateTime dataInserimento { get; set; }
        public string userName { get; set; }
        public System.DateTime data { get; set; }
        public Nullable<System.DateTime> dataUltimaAssunzione { get; set; }
        public int idMotivazione { get; set; }
        public string motivazione { get; set; }
        public byte outcomePrimario { get; set; }
        public Nullable<byte> tumore { get; set; }
        public string tumoreDiagnosi { get; set; }
        public string tumoreSede { get; set; }
        public Nullable<byte> cardiovascolare { get; set; }
        public string cardiovascolareDiagnosi { get; set; }
        public string cardiovascolareDescrizione { get; set; }
        public Nullable<byte> diabeteTipo2 { get; set; }
        public Nullable<byte> altre { get; set; }
        public string altreDiagnosi { get; set; }
        public string altreDescrizione { get; set; }
        public Nullable<System.DateTime> dataDiagnosiPrincipale { get; set; }
    
        public virtual LUDropMotivazioni LUDropMotivazioni { get; set; }
        public virtual StatiRegistro StatiRegistro { get; set; }
    }
}
