//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeMeMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KitRandomizzazione
    {
        public KitRandomizzazione()
        {
            this.KitFlaconiAssegnazione = new HashSet<KitFlaconiAssegnazione>();
        }
    
        public string Kit { get; set; }
        public int Blocco { get; set; }
        public byte[] TreatmentGroup { get; set; }
        public byte[] TreatmentGroupDescription { get; set; }
        public string Contenuto { get; set; }
        public Nullable<System.DateTime> DataConsegna { get; set; }
        public Nullable<System.DateTime> ScadenzaFarmaco { get; set; }
        public string Lotto { get; set; }
        public string Fornitore { get; set; }
        public bool Reso { get; set; }
    
        public virtual ICollection<KitFlaconiAssegnazione> KitFlaconiAssegnazione { get; set; }
    }
}
