//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeMeMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUAE_Grado
    {
        public LUAE_Grado()
        {
            this.AEDettaglio = new HashSet<AEDettaglio>();
        }
    
        public int idAEGrado { get; set; }
        public string grado { get; set; }
    
        public virtual ICollection<AEDettaglio> AEDettaglio { get; set; }
    }
}
