//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeMeMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUIstruzione
    {
        public LUIstruzione()
        {
            this.Anagrafica = new HashSet<Anagrafica>();
        }
    
        public int idIstruzione { get; set; }
        public string istruzione { get; set; }
    
        public virtual ICollection<Anagrafica> Anagrafica { get; set; }
    }
}
