//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeMeMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUTipoTrattamento
    {
        public LUTipoTrattamento()
        {
            this.TrattamentiDettaglio = new HashSet<TrattamentiDettaglio>();
        }
    
        public int idTipoTrattamento { get; set; }
        public string tipoTrattamento { get; set; }
    
        public virtual ICollection<TrattamentiDettaglio> TrattamentiDettaglio { get; set; }
    }
}
