//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeMeMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAE
    {
        public int idSAE { get; set; }
        public int idPaziente { get; set; }
        public System.DateTime dataInserimento { get; set; }
        public string userName { get; set; }
        public string studyDrug { get; set; }
        public Nullable<int> dosaggio { get; set; }
        public string assunzioneSAE { get; set; }
        public System.DateTime dataAssegnazionePeriodoProva { get; set; }
        public System.DateTime dataUltimaAssunzione { get; set; }
        public System.DateTime dataSAE { get; set; }
        public string diagnosi { get; set; }
        public int gravita { get; set; }
        public int relazioneCausale { get; set; }
        public string azioneIntrapresa { get; set; }
        public System.DateTime inizioSAE { get; set; }
        public Nullable<System.DateTime> fineSAE { get; set; }
        public int reazioneArresto { get; set; }
        public int risomministrazioneFarmaco { get; set; }
        public Nullable<System.DateTime> dataRisomministrazioneFarmaco { get; set; }
        public Nullable<int> ripetizioneDopoRiassunzione { get; set; }
        public int risultato { get; set; }
        public Nullable<int> eventoFatale { get; set; }
        public Nullable<System.DateTime> dataMorte { get; set; }
        public Nullable<int> malattiaCausaSAE { get; set; }
        public string concomitante1 { get; set; }
        public string concomitante1Diagnosi { get; set; }
        public string concomitante1DoseGG { get; set; }
        public string concomitante1DaQuanto { get; set; }
        public Nullable<System.DateTime> concomitante1DataInzio { get; set; }
        public Nullable<System.DateTime> concomitante1DataFine { get; set; }
        public Nullable<int> concomitante1InCorso { get; set; }
        public Nullable<int> concomitante1CauseSAE { get; set; }
        public Nullable<int> concomitante1modificaConduzioneTrial { get; set; }
        public string concomitante2 { get; set; }
        public string concomitante2Diagnosi { get; set; }
        public string concomitante2DoseGG { get; set; }
        public string concomitante2DaQuanto { get; set; }
        public Nullable<System.DateTime> concomitante2DataInzio { get; set; }
        public Nullable<System.DateTime> concomitante2DataFine { get; set; }
        public Nullable<int> concomitante2InCorso { get; set; }
        public Nullable<int> concomitante2CauseSAE { get; set; }
        public Nullable<int> concomitante2modificaConduzioneTrial { get; set; }
        public string concomitante3 { get; set; }
        public string concomitante3Diagnosi { get; set; }
        public string concomitante3DoseGG { get; set; }
        public string concomitante3DaQuanto { get; set; }
        public Nullable<System.DateTime> concomitante3DataInzio { get; set; }
        public Nullable<System.DateTime> concomitante3DataFine { get; set; }
        public Nullable<int> concomitante3InCorso { get; set; }
        public Nullable<int> concomitante3CauseSAE { get; set; }
        public Nullable<int> concomitante3modificaConduzioneTrial { get; set; }
        public string malattiaAllergiaRischio1 { get; set; }
        public Nullable<System.DateTime> malattiaAllergiaRischio1DataInizio { get; set; }
        public Nullable<System.DateTime> malattiaAllergiaRischio1DataFine { get; set; }
        public Nullable<int> malattiaAllergiaRischio1InCorso { get; set; }
        public Nullable<int> malattiaAllergiaRischio1CausaPrimariaSAE { get; set; }
        public string malattiaAllergiaRischio2 { get; set; }
        public Nullable<System.DateTime> malattiaAllergiaRischio2DataInizio { get; set; }
        public Nullable<System.DateTime> malattiaAllergiaRischio2DataFine { get; set; }
        public Nullable<int> malattiaAllergiaRischio2InCorso { get; set; }
        public Nullable<int> malattiaAllergiaRischio2CausaPrimariaSAE { get; set; }
        public string malattiaAllergiaRischio3 { get; set; }
        public Nullable<System.DateTime> malattiaAllergiaRischio3DataInizio { get; set; }
        public Nullable<System.DateTime> malattiaAllergiaRischio3DataFine { get; set; }
        public Nullable<int> malattiaAllergiaRischio3InCorso { get; set; }
        public Nullable<int> malattiaAllergiaRischio3CausaPrimariaSAE { get; set; }
        public string osservazioni { get; set; }
    
        public virtual Anagrafica Anagrafica { get; set; }
    }
}
