//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeMeMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatiElenco
    {
        public StatiElenco()
        {
            this.StatiRegistro = new HashSet<StatiRegistro>();
        }
    
        public int idStato { get; set; }
        public string descrizione { get; set; }
        public string descrizioneForm { get; set; }
        public string fase { get; set; }
        public string istruzioni { get; set; }
    
        public virtual ICollection<StatiRegistro> StatiRegistro { get; set; }
    }
}
