//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeMeMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trattamenti
    {
        public Trattamenti()
        {
            this.TrattamentiDettaglio = new HashSet<TrattamentiDettaglio>();
        }
    
        public int idStatoRegistro { get; set; }
        public System.DateTime dataInserimento { get; set; }
        public string userName { get; set; }
        public System.DateTime data { get; set; }
    
        public virtual StatiRegistro StatiRegistro { get; set; }
        public virtual ICollection<TrattamentiDettaglio> TrattamentiDettaglio { get; set; }
    }
}
